flowchart LR
    Analytics -->|"3"| Grading
    Analytics -->|"4"| Identity
    Central -->|"6"| Identity
    Cohorts -->|"1"| ExamSession
    Cohorts -->|"4"| Identity
    Competency -->|"3"| Identity
    Competency -->|"1"| QuestionBank
    ExamEngine -->|"1"| Competency
    ExamEngine -->|"2"| ExamSession
    ExamEngine -->|"1"| Grading
    ExamEngine -->|"3"| Identity
    ExamEngine -->|"4"| QuestionBank
    ExamEngine -->|"1"| Rules
    ExamSession -->|"2"| Cohorts
    ExamSession -->|"8"| ExamEngine
    ExamSession -->|"4"| Grading
    ExamSession -->|"5"| Identity
    ExamSession -->|"1"| Penalties
    ExamSession -->|"3"| Proctoring
    ExamSession -->|"2"| QuestionBank
    ExamSession -->|"2"| Rules
    Grading -->|"1"| Competency
    Grading -->|"6"| ExamEngine
    Grading -->|"16"| ExamSession
    Grading -->|"7"| Identity
    Grading -->|"1"| Penalties
    Grading -->|"1"| Proctoring
    Grading -->|"2"| QuestionBank
    Grading -->|"2"| Workflows
    Penalties -->|"1"| ExamSession
    Penalties -->|"4"| Identity
    Penalties -->|"6"| Proctoring
    Proctoring -->|"7"| ExamSession
    Proctoring -->|"3"| Identity
    QuestionBank -->|"1"| Competency
    QuestionBank -->|"4"| ExamSession
    QuestionBank -->|"1"| Grading
    QuestionBank -->|"7"| Identity
    Rules -->|"1"| ExamEngine
    Rules -->|"1"| Grading
    Rules -->|"3"| Identity
    Workflows -->|"1"| Cohorts
    Workflows -->|"3"| ExamEngine
    Workflows -->|"2"| ExamSession
    Workflows -->|"1"| Grading
    Workflows -->|"10"| Identity
    linkStyle 3 stroke:#D85A30,stroke-width:2px
    linkStyle 6 stroke:#D85A30,stroke-width:2px
    linkStyle 8 stroke:#D85A30,stroke-width:2px
    linkStyle 9 stroke:#D85A30,stroke-width:2px
    linkStyle 12 stroke:#D85A30,stroke-width:2px
    linkStyle 13 stroke:#D85A30,stroke-width:2px
    linkStyle 14 stroke:#D85A30,stroke-width:2px
    linkStyle 15 stroke:#D85A30,stroke-width:2px
    linkStyle 17 stroke:#D85A30,stroke-width:2px
    linkStyle 18 stroke:#D85A30,stroke-width:2px
    linkStyle 19 stroke:#D85A30,stroke-width:2px
    linkStyle 22 stroke:#D85A30,stroke-width:2px
    linkStyle 23 stroke:#D85A30,stroke-width:2px
    linkStyle 27 stroke:#D85A30,stroke-width:2px
    linkStyle 28 stroke:#D85A30,stroke-width:2px
    linkStyle 29 stroke:#D85A30,stroke-width:2px
    linkStyle 32 stroke:#D85A30,stroke-width:2px
    linkStyle 34 stroke:#D85A30,stroke-width:2px
    linkStyle 35 stroke:#D85A30,stroke-width:2px
    linkStyle 36 stroke:#D85A30,stroke-width:2px
    linkStyle 38 stroke:#D85A30,stroke-width:2px
    linkStyle 44 stroke:#D85A30,stroke-width:2px